spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    show-sql: true
    generate-ddl: true
  datasource:
    pageSize: 1000
    primary: # 本地数据库
      name: cloud
      jdbc-url: jdbc:mysql://localhost:3306/cloud
      username: root
      password: taojin1992
      type: mysql
    secondary:  # 源数据库
      name: cloud #数据库名称，mysql使用小写
      jdbc-url: jdbc:mysql://192.168.185.56:35006/cloud
      username: root
      password: FL@AYe5cBs4S
      type: mysql #数据库类型



    #database
    #primary:  # 本地数据库
    #  name: WS #数据库名称，oracle必须使用大写
    #  jdbc-url: jdbc:oracle:thin:@192.168.3.10:1521:orcl
    #  username: ws
    #  password: 123456
    #  type: oracle #数据库类型，
   # secondary:  # 本地数据库
   #   name: WS
   #   jdbc-url: jdbc:oracle:thin:@192.168.3.11:1521:orcl
   #   username: ws
   #   password: 123456
   #   type: oracle